#!/bin/sh

tmpdir=$(mktemp -d /tmp/w3mepub-XXXXXX)
confdir=/usr/local/share/w3mepub
export LESSKEY=${confdir}/less.conf
unset LESS_IS_MORE
unset LESSSECURE

trap 'rm -r "$tmpdir"' 0 1 15

xmltr() {
	xsltproc --stringparam rootdir "${rootdir:-na}" \
		"${confdir}/${1}.xsl" "${tmpdir}/${2}"
}

unzip -q "$1" -d "$tmpdir" || {
	echo Cannot extract
	exit 1
}

fullpath=$(xmltr fullpath META-INF/container.xml)
title=$(xmltr title "$fullpath")
abspath=${tmpdir}/${fullpath}
rootdir=${abspath%/*}

IFS="
"
w3m -config "${confdir}/w3m.conf" -T text/html \
	-cols 65 -dump $(xmltr content "$fullpath") | \
	less
